### ISSUE TITLE
Style: The rounding of the inner element does not correspond to the rounding of the outer element

### ISSUE THREAD

**Issue by yhdgms1** [hyoo-ru/artist.hyoo.ru#1]
![Screenshot_20230227_100336_Edge.jpg](https://user-images.githubusercontent.com/44583679/221496679-dc8d28b0-b9a8-4303-b408-aba43bd02f1f.jpg)

![Screenshot_20230227_100348_Edge.jpg](https://user-images.githubusercontent.com/44583679/221496691-b2619f3e-2c4d-49cc-9013-5d0943dec703.jpg)

**Comment by nin-jin** [comment]
I've done redesign.
![image](https://user-images.githubusercontent.com/442988/221630686-218bb9f8-985f-477b-9161-823fbafb880c.png)
